version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/faceattend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
